project_id = "lxyzuyayzqjzposadsyz"

[functions.pi-payment-approve]
verify_jwt = false

[functions.pi-payment-complete]
verify_jwt = false

[functions.pi-auth]
verify_jwt = false

[functions.subscription]
verify_jwt = false

[functions.pi-ad-verify]
verify_jwt = false

[functions.theme-management]
verify_jwt = true
